FROM golang:1.6
MAINTAINER Octoblu, Inc. <docker@octoblu.com>

WORKDIR /go/src/github.com/octoblu/vulcand-bundle
COPY . /go/src/github.com/octoblu/vulcand-bundle

RUN env CGO_ENABLED=0 go build -o vctl-bundle -a -ldflags '-s' github.com/octoblu/vulcand-bundle/vctl
RUN mv vctl out-of-the-way
RUN mv vctl-bundle vctl

CMD ["./vctl"]
